app_auth/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView

from app_auth.views import LoginView, LogoutView, RegisterView, validate_username

app_name = "app_auth"


urlpatterns = [
    path(
        "me/",
        TemplateView.as_view(template_name="app_auth/me.html"),
        name="about-me",
    ),
    path(
        "login/",
        # TemplateView.as_view(template_name="site_auth/login.html"),
        LoginView.as_view(),
        name="login",
    ),
    path(
        "logout/",
        LogoutView.as_view(),
        name="logout",
    ),
    path(
        "register/",
        RegisterView.as_view(),
        name="register",
    ),
    path("validate_username", validate_username, name="validate_username",),
]

my_app/urls.py
from django.contrib import admin
from django.urls import path
from .views import (
    IndexTemplateView,
    ShowProfile,
    EditProfile,
    get_service,
    index_page,
    get_sms,
    popolnenie,
)

app_name = "my_app"


urlpatterns = [
    path("", index_page, name="index"),
    path("get-service/", get_service, name="get-service"),
    path("popolnenie/", popolnenie, name="popolnenie"),
    path("get-sms/", get_sms, name="get-sms"),
    path("profile/", ShowProfile.as_view(), name="profile"),
    path("profile/edit/<int:pk>/", EditProfile.as_view(), name="profile-edit"),
]

my_otus_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from my_otus_project.settings import DEBUG

urlpatterns = [
    path("admin/", admin.site.urls),
    # path("", IndexTemplateView.as_view(), name="index"),
    path("", include("my_app.urls")),
    path("auth/", include("app_auth.urls")),
]

if DEBUG:
    urlpatterns.extend([
        path("__debug__/", include("debug_toolbar.urls"))
    ],)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

my_app/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
class ProfileUser(models.Model):
    user = models.OneToOneField(
        User, null=True, on_delete=models.CASCADE, related_name="profile"
    )
    balance = models.DecimalField(
        null=False, default=0, max_digits=30, decimal_places=2
    )
    phone = models.CharField(max_length=30, help_text="Required.")
    bio = models.TextField(null=False, blank=True)
    profile_pic = models.ImageField(null=False, blank=True, upload_to="images/profile/")
    facebook = models.CharField(max_length=50, null=False, blank=True)
    twitter = models.CharField(max_length=50, null=False, blank=True)
    instagram = models.CharField(max_length=50, null=False, blank=True)
    telegramm = models.CharField(max_length=50, null=False, blank=True)

    def __str__(self):
        return str(self.user)


class ProfileOperations(models.Model):
    class Status(models.IntegerChoices):
        no_active = 0
        active = 1

    profile = models.ForeignKey(
        "ProfileUser", related_name="operations", on_delete=models.CASCADE, unique=False
    )
    tel = models.CharField(max_length=50, null=False, unique=False)
    id_num = models.CharField(max_length=50, null=False, unique=False)
    release_date = models.DateTimeField(auto_now_add=True)
    status = models.ImageField(
        choices=Status.choices,
    )

    def __str__(self):
        return f"{self.profile.user.username}, {self.tel}, {self.release_date}"

my_app/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import ProfileUser


class ProfileForm(forms.ModelForm):
    class Meta:
        model = ProfileUser
        fields = "profile_pic", "facebook", "twitter", "instagram", "telegramm", "phone"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name, field in self.fields.items():
            print(name, field)
            field: forms.Field
            widget: forms.Widget = field.widget
            widget.attrs["class"] = "form-control"
            if isinstance(field, forms.CharField):
                print(field.label, type(field.label))


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = "first_name", "last_name", "email"

my_app/views.py
import json

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView, UpdateView, ListView
from VakSmsApi import VakSmsApi
import requests
from .forms import (
    ProfileForm,
)
from .models import ProfileUser, ProfileOperations

api = VakSmsApi(api_key="c230a5896a6e4ab1a743d07a0340fc78")
API = "c230a5896a6e4ab1a743d07a0340fc78"

a = {
    "OpenAI": "dr",
    "Cupis": "cp",
    "Tinkoff": "tf",
    "QIWl Wallet": "qw",
    "VK - MailRu": "mr",
    "Netflix": "nf",
    "AliExpress": "ai",
    "Юmoney": "ym",
    "Nike": "nk",
    "Protonmail": "pm",
    "WhatsApp": "wa",
    "Twitter": "tw",
    "Yahoo": "yh",
    "Yalla": "ll",
    "AOL": "ao",
    "Discord": "dc",
    "Facebook": "fb",
    "WeChat": "wc",
    "Instagram": "ig",
    "PayPal": "pp",
    "WebMoney": "wm",
    "AirBnb": "ab",
    "Yandex": "ya",
    "Google": "gl",
    "Uber": "ub",
    "Вкусно и точка": "md",
    "Tinder": "td",
    "Telegram": "tg",
    "Line messenger": "lm",
    "Tiktok": "tk",
    "Microsoft": "ms",
    "Viber": "vi",
    "Tencent QQ": "qq",
    "Steam": "st",
    "Coffee LIKE": "ec",
    "Checkscan": "chs",
    "Greggs": "eg",
    "Grindr": "gd",
    "thediversity": "hi",
    "Paysend": "pd",
    "Kraisbonus": "kb",
    "Rencredit": "rc",
    "Золотое Яблоко": "gap",
    "Citilink": "cl",
    "Winelab": "wn",
    "Letual": "le",
    "Технопарк": "tpk",
    "holodilnik.ru": "hld",
    "Mozen": "mz",
    "Weplay": "pw",
    "Epicnpc": "nc",
    "vsesmart": "va",
    "TaxiMaxim": "tm",
    "Casino Online": "co",
    "FixPrice": "fp",
    "stalker-co": "str",
    "remi": "rmi",
    "Lazada": "dl",
    "hh.ru": "hh",
    "bethowen.ru": "bth",
    "salton-promo": "spr",
    "kotanyipromo": "ktn",
    "namars": "mrs",
    "VTB": "vt",
    "internetopros": "io",
    "Ebay": "eb",
    "DiDi taxi": "dd",
    "Twitch": "th",
    "Верный": "vn",
    "Vsesmart.ru": "sar",
    "Amazon": "am",
    "Cstar": "rx",
    "24u": "24u",
    "Coolclever": "cv",
    "Tilda": "ld",
    "Weco": "wo",
    "СберМегаМаркет": "smm",
    "Atlasbus.by": "atl",
    "Vivaldi": "vd",
    "Mobileproxy": "my",
    "Alfa-Bank": "af",
    "SberCloud": "scd",
    "TradingView": "tv",
    "Аптеки": "at",
    "Золотая Корона": "zk",
    "MyBeautyBonus": "yb",
    "Stormgain": "sn",
    "Seafood-shop": "sfs",
    "Getcontact": "gc",
    "ПочтаБанк": "pbk",
    "Apple": "al",
    "ФКХК": "fkhk",
    "Zhihu": "zu",
    "kopilkaclub": "kc",
    "MyGLO": "ae",
    "Кошелек": "cm",
    "Bumble": "bm",
    "Tatneft": "tn",
    "LOVE": "lv",
    "Lukoil": "lkl",
    "Regru": "rr",
    "Taobao": "tb",
    "Ogon": "og",
    "AliPay": "ap",
    "Страховые": "strh",
    "Петрович": "ph",
    "etxt.biz": "txt",
    "Tanuki": "ti",
    "Rutube": "rtb",
    "nloto": "nlt",
    "ЧитайГород": "chg",
    "Ак Барс Банк": "ak",
    "Твоё": "ty",
    "Move": "xc",
    "Веб хостинги": "bg",
    "MVideo": "mv",
    "СберМаркет": "sm",
    "Столото": "sl",
    "Киносервисы": "ks",
    "Raiffeisen": "rf",
    "Onrealt": "or",
    "Вкусвилл": "vv",
    "KFC": "kf",
    "Ашан": "au",
    "Battle": "xn",
    "Signal": "sig",
    "Burger King": "bk",
    "Profi": "prf",
    "Deliveroo": "do",
    "Tom-tailor": "tot",
    "Novex": "nx",
    "Шоколадница": "shc",
    "JumpTaxi": "jt",
    "Premium one": "ta",
    "IQOS": "iqs",
    "Buff.163": "bf",
    "Vodorobot": "vr",
    "budget4me-34": "bgp",
    "Biglion": "bl",
    "Ostin": "on",
    "Спортмастер": "sa",
    "Мята lounge": "mlg",
    "KazanExpress": "ke",
    "Кикшеринг": "sk",
    "banki.ru": "br",
    "ДругВокруг": "dv",
    "Ozon": "oz",
    "KNP24": "kn",
    "Drom": "hz",
    "DoDo pizza": "dp",
    "Avito": "av",
    "Remit": "re",
    "Wildberries": "wb",
    "Inbox lv": "il",
    "X5ID": "x5",
    "Book24": "b24",
    "Marlboro": "mrl",
    "LinkedIn": "ln",
    "Магнит": "mg",
    "IMO messanger": "im",
    "Beela Chat": "ba",
    "Perfluence": "pf",
    "inDriver": "rl",
    "Wooppay": "wp",
    "mail.kz": "mkz",
    "Blablacar": "bb",
    "Steemit": "ste",
    "OLX": "ox",
    "Farpost": "fr",
    "32Red": "rd",
    "Naver": "nv",
    "Unistream": "us",
    "Coinbase": "cb",
    "werewolf.53site": "wer",
    "Getir": "ge",
    "Battle": "bt",
    "FreeCash": "fc",
    "Monese": "me",
    "Rocketreach": "rk",
    "Whitecard": "wt",
    "bet365": "ef",
    "Ticketmaster.com": "tz",
    "Ftx": "fx",
    "Dropverse": "dro",
    "Weststeincard": "wcd",
    "Paysafecard": "pc",
    "Craigslist": "crg",
    "Okcupid": "oc",
    "Yubo": "yu",
    "Сoursehero": "coh",
    "rediff.com": "rdf",
    "GroupMe": "gm",
    "Revolut": "rt",
    "Ultra.io": "uo",
    "4FunLite": "fl",
    "1688": "hn",
    "Foodpanda": "fa",
    "Weibo": "wi",
    "Bigo Live": "be",
    "Ace2three": "ac",
    "inpost.pl": "inp",
    "Communitygaming": "cg",
    "Rediff.com": "mrf",
    "Alfagift": "ag",
    "Shopee": "sh",
    "Fameex": "fm",
    "Blibli": "fk",
    "Ovo": "oo",
    "Gojek": "gj",
    "DANA": "dn",
    "Jingdong": "jd",
    "Badoo": "jz",
    "Snapchat": "fu",
    "alias_": "als",
    "PaxFul": "xf",
    "OfferUp": "zm",
    "Bolt": "ol",
    "Blockchain": "bc",
    "Faceit": "qz",
    "CryptoCom": "ry",
    "Dundle": "fi",
    "stripe": "je",
    "Yoshidrops": "yd",
    "KakaoTalk": "kt",
    "Kaggle": "kg",
    "Магнолия": "mn",
    "Yamaguchi": "yam",
    "УМ": "um",
    "Zoon": "zn",
    "Суточно": "sy",
    "2domains": "dom",
    "Sravni.ru": "ra",
    "Azsirbis": "az",
    "Selectel": "se",
    "Улыбка радуги": "xa",
    "РосБанк": "rb",
    "Bavarushka": "vs",
    "Едем.рф": "ed",
    "Privetmir": "pi",
    "Kvartplata.ru": "kp",
    "VseInstrumenti": "vsi",
    "Совкомбанк": "sb",
    "youdo": "ud",
    "Litnet": "et",
    "Sokolov": "sv",
    "Мой-ка": "ik",
    "Rosneft": "rn",
    "NationalLottery": "nl",
    "Leadgid.com": "lg",
    "FancyLive": "vf",
    "Trovo": "ov",
    "Сушкоф": "qx",
    "Yappy": "kj",
    "Билеты в кино": "zj",
    "Cian": "ca",
    "ЯRUS": "yr",
    "blok-post.ru": "blp",
    "Cofix": "cf",
    "Лента": "lt",
    "Solar-staff": "ss",
    "150bar": "ar",
    "СДЭК": "dk",
    "El-plat": "ep",
    "Газпром": "gp",
    "Galamart": "gal",
    "Pivko24": "pv",
    "RuVDS": "rv",
    "Hoff": "ho",
    "Xiaomi": "xi",
    "Checkin": "ci",
    "Blizzard": "bz",
    "Huya.com": "hy",
}
SERVICES = dict((v, k) for k, v in a.items())


def get_list_services(country, operator):
    url = f"https://vak-sms.com/api/getCountNumberList/?apiKey={API}&country={country}&operator={operator}&price"
    response = requests.get(url)
    if response.status_code == 200:
        return response.json()
    else:
        raise Exception(response.status_code)


@login_required
def get_service(request):
    if request.method == "POST":
        service = request.POST.get("service")
        url = f"https://vak-sms.com/api/getNumber/?apiKey={API}&service={service}&country=ru&operator=mts"
        services = get_list_services(country="ru", operator="mts")
        if request.user.profile.balance < int(services[service]['price']):
            return JsonResponse(
                {
                    "error": "noMoney",
                    "price": int(services[service]['price']),
                },
                content_type="application/json",
            )
        response = requests.get(url)
        price = int(services[service]["price"])
        if response.status_code == 200:
            context_service = response.json()
            print(dict(context_service).get("error"))
            if context_service.get("error"):
                return JsonResponse(
                    {
                        "error": context_service,
                        "price": price,
                    },
                    content_type="application/json",
                )
            else:
                print(context_service)
                operation = ProfileOperations(
                    profile=request.user.profile,
                    tel=context_service["tel"],
                    id_num=context_service["idNum"],
                    status="1",
                )
                operation.save()
                return JsonResponse(
                    {
                        "tel": context_service["tel"],
                        "id": context_service["idNum"],
                        "price": price,
                    },
                    content_type="application/json",
                )
        else:
            raise Exception(response.status_code)
    else:
        qr = dict(get_list_services(country="ru", operator="mts")).items()

        return render(
            request,
            "my_app/index.html",
            context={
                "services": qr,
            },
        )


def get_sms(request: HttpRequest):
    if request.method == "POST":
        id = request.POST.get("id")
        url = f"https://vak-sms.com/api/getSmsCode/?apiKey={API}&idNum={id}"
        response = requests.get(url)
        sms = response.json()
        print(sms, id)
        return JsonResponse(
            {
                "sms": sms["smsCode"],
            },
            content_type="application/json",
        )


@login_required
def popolnenie(request: HttpRequest):
    if request.method == "POST":
        new_balance = request.POST.get("money")

        profile = ProfileUser.objects.get(pk=request.user.profile.pk)
        profile.balance += int(new_balance)
        profile.save()
        return redirect("my_app:index")

    return render(request=request, template_name="my_app/popolnenie.html")

my_app/templates/my_app/index.html
{% extends 'base.html' %}
{% load static %}
{% load get_dict_val %}
{% block title %}
    Index page
{% endblock %}
<script src="{% static "admin/css/base.css" %}"></script>
<script src="{% static "admin/css/base.css" %}"></script>
{% block body %}
    <div class="row">
        <div class="col-sm">
            <form method="post" id="services" enctype="multipart/form-data">
                {% csrf_token %}
                <ul id="services-list" class="list-group row">
                    {% for name, field in services %}
                        {% if services_name|get_item:name %}
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                <div class="col-sm">
                                    <img class="icon" src="static/admin/img/services/{{ name }}.png"
                                         alt="">
                                </div>
                                <div class="col-sm">
                                    {{ services_name|get_item:name }}
                                </div>
                                <div class="col-sm">
                                    <span class="badge bg-primary rounded-pill">
                                    {{ field.count }} шт.
                                    </span>
                                </div>
                                <div class="col-sm">
                                    <span id="balance" class="badge bg-warning rounded-pill">
                                        {{ field.price }} руб.
                                    </span>
                                </div>
                                <br/>
                                <!-- Добавьте нужные данные в элемент data-id -->
                                <input hidden="display-block" type="hidden" name="service" value="{{ name }}"
                                       data-id="{{ field.count }}" data-balance="{{ field.price }}"/>
                                {% if request.user.is_authenticated %}
                                    <button class="btn btn-primary" type="submit">Получить</button>
                                {% else %}
                                    <a href="{% url 'app_auth:login' %}" class="btn btn-primary">Получить</a>
                                {% endif %}
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </form>
        </div>
        <div class="col-sm">
            <div id="chat-container" class="row" style="display: none">
                <a id="icon-link" class="icon">
                    <svg viewBox="64 64 896 896" data-icon="reload" width="1em" height="1em" fill="currentColor"
                         aria-hidden="true" focusable="false" class="">
                        <path d="M909.1 209.3l-56.4 44.1C775.8 155.1 656.2 92 521.9 92 290 92 102.3 279.5 102 511.5 101.7 743.7 289.8 932 521.9 932c181.3 0 335.8-115 394.6-276.1 1.5-4.2-.7-8.9-4.9-10.3l-56.7-19.5a8 8 0 0 0-10.1 4.8c-1.8 5-3.8 10-5.9 14.9-17.3 41-42.1 77.8-73.7 109.4A344.77 344.77 0 0 1 655.9 829c-42.3 17.9-87.4 27-133.8 27-46.5 0-91.5-9.1-133.8-27A341.5 341.5 0 0 1 279 755.2a342.16 342.16 0 0 1-73.7-109.4c-17.9-42.4-27-87.4-27-133.9s9.1-91.5 27-133.9c17.3-41 42.1-77.8 73.7-109.4 31.6-31.6 68.4-56.4 109.3-73.8 42.3-17.9 87.4-27 133.8-27 46.5 0 91.5 9.1 133.8 27a341.5 341.5 0 0 1 109.3 73.8c9.9 9.9 19.2 20.4 27.8 31.4l-60.2 47a8 8 0 0 0 3 14.1l175.6 43c5 1.2 9.9-2.6 9.9-7.7l.8-180.9c-.1-6.6-7.8-10.3-13-6.2z"></path>
                    </svg>
                </a>
                <div>
                    <ul class="list-group">
                        <li class="list-group-item colm-sm">
                                 <span class="badge  rounded-pill">
                                <svg xmlns="http://www.w3.org/2000/svg" id="f0AiQzMHtn_1357" viewBox="0 0 640 480"
                                     height="16" width="22">
                                    <g fill-rule="evenodd" stroke-width="1pt">
                                        <path fill="#fff" d="M0 0h640v480H0z"></path>
                                        <path fill="#0039a6" d="M0 160h640v320H0z"></path>
                                        <path fill="#d52b1e" d="M0 320h640v160H0z"></path>
                                    </g>
                                </svg>
                                 </span>
                            <span id="tel_number" class="rounded-pill">
                                {{ number }}
                            </span>
                            <span id="idNum" class="" style="display: none"></span>
                        </li>
                        <li class="list-group-item">

                            <span id="sms" class="">
                                Здесь будет отображаться ваше СМС
                            </span>
                        </li>
                </div>
            </div>
        </div>
    </div>
    <div id="result"></div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        const iconLink = document.getElementById("icon-link");

        iconLink.addEventListener("click", function () {
            iconLink.style.borderRadius = "50%";
        });
    </script>
    <script>
        $(document).ready(function () {
            $('.btn-primary').on('click', function (event) {
                event.preventDefault();

                var selectedService = $(this).closest('li').find('[name="service"]').val(); // Получение выбранного значения

                $.ajax({
                    type: 'POST',
                    url: '{% url "my_app:get-service" %}', // URL адрес вашего представления Django
                    data: {
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                        service: selectedService // Добавление выбранного значения
                    },
                    success: function (response) {
                        {#// Обработка ответа от представления Django#}

                        console.log(response);

                        if (response.price > {{ request.user.profile.balance }}) {
                            alert('Недостаточно средств на балансе!');
                        } else {
                            $("#tel_number").text(response.tel);
                            $("#idNum").text(response.id);
                            $("#chat-container").show();
                            $("#tel_number").show();

                        }
                    }
                });
            });
        });
    </script>
    <script>
        $(document).ready(function () {
            $("#icon-link").on('click', function (event) {
                event.preventDefault();

                var idNum = $("#idNum").text();

                $.ajax({
                    type: 'POST',
                    url: '{% url "my_app:get-sms" %}', // URL адрес вашего представления Django
                    data: {
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                        id: idNum,
                    },
                    success: function (response) {
                        {#// Обработка ответа от представления Django#}
                        if (response.sms.text != NaN) {

                            $('#sms').text(response.sms);
                        }
                    }
                });
            });
        });
    </script>
{% endblock %}
{% block javascript %}
{% endblock %}

my_app/templates/my_app/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Profile Page
{% endblock %}

{% block body %}
    <div class="container">
        <div class="main-body">
            <div class="row gutters-sm">
                <div class="col-md-4 mb-3">
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex flex-column align-items-center text-center">
                                {% if profile.profile_pic %}
                                    <img src="{{ profile.profile_pic.url }}" height=100 width=100><br><br>
                                {% else %}
                                    <img src="{% static 'admin/img/user.png' %}" height=100 width=100><br><br>
                                {% endif %}
                            <h4>{{ user }}</h4>
                            <h6>Balance: <code>{{ profile.balance }}</code></h6>
                            </div>
                        </div>
                    </div>
                    <div class="card mt-3">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h6 class="mb-0">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                         fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                         stroke-linejoin="round"
                                         class="feather feather-twitter mr-2 icon-inline text-info">
                                        <path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path>
                                    </svg>
                                    Twitter
                                </h6>
                                <span class="text-secondary">{{ profile.twitter }}</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h6 class="mb-0">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                         fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                         stroke-linejoin="round"
                                         class="feather feather-instagram mr-2 icon-inline text-danger">
                                        <rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect>
                                        <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path>
                                        <line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line>
                                    </svg>
                                    Instagram
                                </h6>
                                <span class="text-secondary">{{ profile.instagram }}</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h6 class="mb-0">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                         fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                         stroke-linejoin="round"
                                         class="feather feather-facebook mr-2 icon-inline text-primary">
                                        <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path>
                                    </svg>
                                    Facebook
                                </h6>
                                <span class="text-secondary">{{ profile.facebook }}</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h6 class="mb-0">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                         fill="None" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                         stroke-linejoin="round"
                                         class="telegram-button mr-2 icon-inline text-primary">
                                        <path d="M23.91 3.79L20.3 20.84c-.25 1.21-.98 1.5-2 .94l-5.5-4.07-2.66 2.57c-.3.3-.55.56-1.1.56-.72 0-.6-.27-.84-.95L6.3 13.7l-5.45-1.7c-1.18-.35-1.19-1.16.26-1.75l21.26-8.2c.97-.43 1.9.24 1.53 1.73z"></path>
                                    </svg>
                                    Telegramm
                                </h6>
                                <span class="text-secondary">{{ profile.telegramm }}</span>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="card mb-3">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">First Name</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    {{ user.first_name }}
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Last Name</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    {{ user.last_name }}
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Email</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    {{ user.email }}
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Phone</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    {{ profile.phone }}
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-12">
                                    <a class="btn btn-info "
                                       href="{% url 'my_app:profile-edit' pk=request.user.profile.pk %}">Edit</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

my_app/templates/my_app/profile_edit1.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Profile Page
{% endblock %}
{% load widget_tweaks %}
{% block body %}
    <form method="post">
{#        {{ form.as_p }}#}
        <div class="form-group">
            Facebook:
            {% render_field form.facebook class="form-control" placeholder="Facebook" type="text" %}
        </div>
        <div class="col-sm-9 text-secondary">
            {% csrf_token %}
            <input type="submit" class="btn btn-primary px-4" value="Save Changes">

        </div>
    </form>
{% endblock %}

my_app/templates/my_app/register.html
{% extends 'base.html' %}
{% block title %}
	AJAX
{% endblock %}

{% block body %}
<div class="col-lg-4">
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" class="form-control mb-3" id="username" placeholder="Username">
    <input type="password" class="form-control mb-3" placeholder="Password">
    <input type="password" class="form-control mb-3" placeholder="Repeat Password">
    <input type="button" value="Submit" class="btn btn-primary">
</form>
</div>
{% endblock %}