app_auth/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView

from app_auth.views import LoginView, LogoutView, RegisterView, validate_username

app_name = "app_auth"


urlpatterns = [
    path(
        "me/",
        TemplateView.as_view(template_name="app_auth/me.html"),
        name="about-me",
    ),
    path(
        "login/",
        # TemplateView.as_view(template_name="site_auth/login.html"),
        LoginView.as_view(),
        name="login",
    ),
    path(
        "logout/",
        LogoutView.as_view(),
        name="logout",
    ),
    path(
        "register/",
        RegisterView.as_view(),
        name="register",
    ),
    path("validate_username", validate_username, name="validate_username",),
]

my_app/urls.py
from django.contrib import admin
from django.urls import path
from .views import (
    IndexTemplateView,
    ShowProfile,
    EditProfile,
    get_service,
    index_page,
    get_sms,
    popolnenie,
)

app_name = "my_app"


urlpatterns = [
    path("", index_page, name="index"),
    path("get-service/", get_service, name="get-service"),
    path("popolnenie/", popolnenie, name="popolnenie"),
    path("get-sms/", get_sms, name="get-sms"),
    path("profile/", ShowProfile.as_view(), name="profile"),
    path("profile/edit/<int:pk>/", EditProfile.as_view(), name="profile-edit"),
]

my_otus_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from my_otus_project.settings import DEBUG

urlpatterns = [
    path("admin/", admin.site.urls),
    # path("", IndexTemplateView.as_view(), name="index"),
    path("", include("my_app.urls")),
    path("auth/", include("app_auth.urls")),
]

if DEBUG:
    urlpatterns.extend([
        path("__debug__/", include("debug_toolbar.urls"))
    ],)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'admin/img/img_1.png' %}">
    <link href="{% static 'admin/css/base.css' %}">
    <link href="{% static 'admin/js/core.js' %}">
    <title>{% block title %}
        Base
    {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

<body>
<nav class="px-3 navbar navbar-expand-sm bg-body-tertiary my-0 my-md-1">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">App</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        {% if user.is_authenticated %}
            <ul class="navbar-nav justify-content-end dropdown-menu-end me-auto mb-2 mb-lg-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                   aria-expanded="false">
                    {{ request.user.profile }}
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a class="dropdown-item"
                           href="{% url 'my_app:profile' %}">Profile</a>
                    </li>
                    <li>
                        <a class="dropdown-item"
                           href="{% url 'my_app:popolnenie' %}">Balance: {{ request.user.profile.balance }}</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link justify-content-end" href="{% url 'app_auth:logout' %}">Logout</a>
            </li>
        {% else %}
            <ul class="navbar-nav justify-content-end dropdown-menu-end me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link justify-content-end" href="{% url 'app_auth:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link justify-content-end" href="{% url 'app_auth:register' %}">Register</a>
                </li>
            </ul>
        {% endif %}
        </ul>
    </div>
</nav>
<div class="container">

    {% block body %}

    {% endblock %}
    {% block javascript %}{% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
	Index page
{% endblock %}

{% block body %}
    <h1>Index page</h1>
	<ul>
    <li>
        <a href="{% url 'my_app:profile' %}">Profile</a>
    </li>
    </ul>
{% endblock %}